import { useCallback, useEffect, useRef, useState } from "react";
import { Analytics } from "@vercel/analytics/react";
import { DEFAULT_PROJECT } from "./config";
import { buildCosenseUrl, extractSharedContent, stripCosenseBody } from "./lib/cosense";
import {
  addProject,
  deleteProject,
  getAiProvider,
  getBodyTemplate,
  getDefaultProject,
  getLinkOpenMode,
  getOpenRouterApiKey,
  getOpenRouterModel,
  getProjects,
  getTitlePrefix,
  setAiProvider,
  setBodyTemplate,
  setDefaultProject,
  setLinkOpenMode,
  setOpenRouterApiKey,
  setOpenRouterModel,
  setTitlePrefix,
  updateProject,
  type AiProvider,
  type Project,
} from "./lib/db";
import { openCosenseUrl, type LinkOpenMode } from "./lib/openExternal";
import type { SharedContent } from "./lib/cosense";
import { isWindowAiAvailable, selectProjectWithAi } from "./lib/aiSelect";
import { checkPageExists } from "./lib/existsCheck";
import { selectProjectWithOpenRouter } from "./lib/openRouterSelect";
import { fetchTitleSource } from "./lib/fetchTitle";
import { generateTitleFromText } from "./lib/generateTitle";
import { SHARED_TEXT_MAX_LENGTH } from "./lib/cosense";
import { X_TITLE_MAX_LENGTH, isXPostUrl, truncateText, truncateTitle } from "./lib/xPost";
import "./App.css";

type View = "generate" | "usage" | "settings";

function buildBody(template: string, url: string, text: string, rawTitle: string): string {
  let body = template
    .replaceAll("{{url}}", url)
    .replaceAll("{{text}}", text)
    .replaceAll("{{title}}", rawTitle);
  body = body.replaceAll("{{date}}", new Date().toISOString().slice(0, 10));
  if (!body.trim()) {
    body = text || url;
  }
  return body;
}

function isValidHttpUrl(value: string): boolean {
  try {
    const u = new URL(value);
    return u.protocol === "http:" || u.protocol === "https:";
  } catch {
    return false;
  }
}

export default function App() {
  const [view, setView] = useState<View>("generate");
  const [inputUrl, setInputUrl] = useState("");
  const [inputText, setInputText] = useState("");
  const [title, setTitle] = useState<string | null>(null);
  const [cosenseUrl, setCosenseUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [includeBodyInLink, setIncludeBodyInLink] = useState(false);
  const initialSharedRef = useRef<SharedContent | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  const [projects, setProjects] = useState<Project[]>([]);
  const [defaultProject, setDefaultProjectState] = useState<string>(DEFAULT_PROJECT);
  const [projectsLoading, setProjectsLoading] = useState(true);
  const [projectForm, setProjectForm] = useState({ name: "", description: "", isPublic: false });
  const [editingName, setEditingName] = useState<string | null>(null);
  const [isProjectDialogOpen, setIsProjectDialogOpen] = useState(false);
  const [projectError, setProjectError] = useState<string | null>(null);
  const [aiProvider, setAiProviderState] = useState<AiProvider>("windowAi");
  const [windowAiAvailable, setWindowAiAvailable] = useState(false);
  const [selectedProject, setSelectedProject] = useState<string | null>(null);
  const [openRouterApiKey, setOpenRouterApiKeyState] = useState("");
  const [openRouterModel, setOpenRouterModelState] = useState("google/gemini-3.7-flash");
  const [titlePrefix, setTitlePrefixState] = useState("");
  const [bodyTemplate, setBodyTemplateState] = useState("{{url}}");
  const [linkOpenMode, setLinkOpenModeState] = useState<LinkOpenMode>("auto");
  const [pageExists, setPageExists] = useState<boolean | null>(null);
  const [checkingExists, setCheckingExists] = useState(false);
  const [generatedBody, setGeneratedBody] = useState<string | null>(null);
  const [aiSuggestedProject, setAiSuggestedProject] = useState<string | null>(null);
  const [lastFetchedUrl, setLastFetchedUrl] = useState<string | null>(null);
  const [lastFetchedText, setLastFetchedText] = useState<string | null>(null);
  const [titleCandidates, setTitleCandidates] = useState<Array<{ label: string; value: string }>>(
    [],
  );
  const [candidateAiLoading, setCandidateAiLoading] = useState(false);
  const [showCandidates, setShowCandidates] = useState(false);
  const candidatesButtonRef = useRef<HTMLButtonElement>(null);
  const candidatesPopoverRef = useRef<HTMLDivElement>(null);
  const [textCandidates, setTextCandidates] = useState<Array<{ label: string; value: string }>>([]);
  const [showTextCandidates, setShowTextCandidates] = useState(false);
  const textCandidatesButtonRef = useRef<HTMLButtonElement>(null);
  const textCandidatesPopoverRef = useRef<HTMLDivElement>(null);
  const lastRawTitleRef = useRef("");

  const loadProjects = useCallback(async () => {
    try {
      const [all, def, provider, orKey, orModel, prefix, bodyTpl, openMode] = await Promise.all([
        getProjects(),
        getDefaultProject(),
        getAiProvider(),
        getOpenRouterApiKey(),
        getOpenRouterModel(),
        getTitlePrefix(),
        getBodyTemplate(),
        getLinkOpenMode(),
      ]);
      setProjects(all);
      setDefaultProjectState(def ?? "");
      setAiProviderState(provider);
      setWindowAiAvailable(isWindowAiAvailable());
      setOpenRouterApiKeyState(orKey);
      setOpenRouterModelState(orModel);
      setTitlePrefixState(prefix);
      setBodyTemplateState(bodyTpl);
      setLinkOpenModeState(openMode);
    } finally {
      setProjectsLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadProjects();
  }, [loadProjects]);

  useEffect(() => {
    setWindowAiAvailable(isWindowAiAvailable());
  }, []);

  const generate = useCallback(
    async (rawUrl: string, rawText: string, rawSharedTitle?: string | null) => {
      const trimmedUrl = rawUrl.trim();
      const trimmedText = truncateText(rawText.trim(), SHARED_TEXT_MAX_LENGTH);
      const sharedTitle = rawSharedTitle?.trim() ? truncateText(rawSharedTitle.trim(), 500) : "";
      const hasUrl = trimmedUrl !== "" && isValidHttpUrl(trimmedUrl);
      const hasText = trimmedText !== "";
      const hasSharedTitle = sharedTitle !== "";
      if (!hasUrl && !hasText && !hasSharedTitle) {
        return;
      }

      setLoading(true);
      setError(null);
      setCopied(false);
      setTitleCandidates([]);
      setCandidateAiLoading(false);
      setShowCandidates(false);
      setTextCandidates([]);
      setShowTextCandidates(false);
      try {
        let fetchedTitle = "";
        let titleTag = "";
        let ogTitle = "";
        let description = "";
        if (hasUrl) {
          const source = await fetchTitleSource(trimmedUrl);
          fetchedTitle = source.title;
          titleTag = source.titleTag;
          ogTitle = source.ogTitle;
          description = source.description;
        }

        const canUseAi =
          aiProvider !== "none" &&
          (aiProvider === "openRouter"
            ? openRouterApiKey.trim() !== ""
            : aiProvider === "windowAi"
              ? windowAiAvailable
              : false);
        const shouldTryAiForText = hasText && canUseAi;
        const shouldTryAiForDesc = !!description && canUseAi && description !== trimmedText;

        // Build candidates from fetch
        const buildFetchCandidates = (): Array<{ label: string; value: string }> => {
          const list: Array<{ label: string; value: string }> = [];
          if (titleTag) list.push({ label: "<title>", value: titleTag });
          if (ogTitle && ogTitle !== titleTag) list.push({ label: "og:title", value: ogTitle });
          if (
            fetchedTitle &&
            fetchedTitle !== titleTag &&
            fetchedTitle !== ogTitle &&
            // for X posts, fetchedTitle is derived from description
            !list.some((c) => c.value === fetchedTitle)
          ) {
            list.push({ label: "取得タイトル", value: fetchedTitle });
          }
          return list;
        };

        let rawTitle: string;
        let candidates: Array<{ label: string; value: string }> = [];
        let aiFromText: string | null = null;
        let aiFromDesc: string | null = null;

        const addAiCandidate = (label: string, value: string, skipRawValue?: string) => {
          if (!value || value === skipRawValue) return;
          setTitleCandidates((prev) => {
            if (prev.some((c) => c.value === value)) return prev;
            return [...prev, { label, value }];
          });
        };

        if (hasSharedTitle) {
          rawTitle = sharedTitle;
          candidates = buildFetchCandidates().filter((c) => c.value !== rawTitle);
          setTitleCandidates(candidates);
          const tasks: Array<Promise<void>> = [];
          if (shouldTryAiForText) {
            tasks.push(
              (async () => {
                const generated = await generateTitleFromText({
                  text: trimmedText,
                  url: hasUrl ? trimmedUrl : null,
                  aiProvider,
                  openRouterApiKey,
                  openRouterModel,
                });
                if (generated && generated !== rawTitle) {
                  aiFromText = generated;
                  addAiCandidate("AI生成（テキスト）", generated, rawTitle);
                }
              })(),
            );
          }
          if (shouldTryAiForDesc) {
            tasks.push(
              (async () => {
                const generated = await generateTitleFromText({
                  text: description,
                  url: hasUrl ? trimmedUrl : null,
                  aiProvider,
                  openRouterApiKey,
                  openRouterModel,
                });
                if (generated && generated !== rawTitle) {
                  aiFromDesc = generated;
                  addAiCandidate("AI生成（説明）", generated, rawTitle);
                }
              })(),
            );
          }
          if (tasks.length > 0) {
            setCandidateAiLoading(true);
            try {
              await Promise.all(tasks);
            } finally {
              setCandidateAiLoading(false);
            }
          }
        } else if (hasText) {
          // No shared title, text-driven (previous logic) - generate both AIs in parallel
          const tasks: Array<Promise<void>> = [];
          if (shouldTryAiForText) {
            tasks.push(
              (async () => {
                const generated = await generateTitleFromText({
                  text: trimmedText,
                  url: hasUrl ? trimmedUrl : null,
                  aiProvider,
                  openRouterApiKey,
                  openRouterModel,
                });
                if (generated) aiFromText = generated;
              })(),
            );
          }
          if (shouldTryAiForDesc) {
            tasks.push(
              (async () => {
                const generated = await generateTitleFromText({
                  text: description,
                  url: hasUrl ? trimmedUrl : null,
                  aiProvider,
                  openRouterApiKey,
                  openRouterModel,
                });
                if (generated) aiFromDesc = generated;
              })(),
            );
          }
          if (tasks.length > 0) {
            setCandidateAiLoading(true);
            try {
              await Promise.all(tasks);
            } finally {
              setCandidateAiLoading(false);
            }
          }
          if (aiFromText) {
            rawTitle = aiFromText;
          } else {
            rawTitle = truncateTitle(trimmedText);
          }
          const fetchCands = buildFetchCandidates().filter((c) => c.value !== rawTitle);
          candidates = [...fetchCands];
          if (aiFromText && aiFromText !== rawTitle) {
            if (!candidates.some((c) => c.value === aiFromText)) {
              candidates.push({ label: "AI生成（テキスト）", value: aiFromText });
            }
          } else if (aiFromText && aiFromText === rawTitle) {
            // default is AI from text, don't duplicate
          }
          if (
            aiFromDesc &&
            aiFromDesc !== rawTitle &&
            !candidates.some((c) => c.value === aiFromDesc)
          ) {
            candidates.push({ label: "AI生成（説明）", value: aiFromDesc });
          }
          setTitleCandidates(candidates);
        } else {
          // URL only (or sharedTitle already handled) - try AI from description
          if (shouldTryAiForDesc) {
            setCandidateAiLoading(true);
            try {
              const generated = await generateTitleFromText({
                text: description,
                url: trimmedUrl,
                aiProvider,
                openRouterApiKey,
                openRouterModel,
              });
              if (generated) aiFromDesc = generated;
            } finally {
              setCandidateAiLoading(false);
            }
          }
          if (aiFromDesc) {
            rawTitle = aiFromDesc;
            candidates = buildFetchCandidates().filter((c) => c.value !== rawTitle);
            // AI from description is the default, don't duplicate
          } else {
            rawTitle = fetchedTitle;
            candidates = buildFetchCandidates().filter((c) => c.value !== rawTitle);
            // Still add AI from description as candidate if it was generated but not default? handled above
            // For URL only, aiFromDesc is the AI, already handled as default, so no extra
          }
          setTitleCandidates(candidates);
          // Also add AI from description as candidate when it is not the default? already handled
          // For URL only, if AI succeeded it is default, otherwise no AI candidate
          // If we want to show AI(desc) as candidate even when default is sharedTitle, that's handled in hasSharedTitle branch
        }
        const finalTitle = `${titlePrefix}${rawTitle}`;
        // 本文テキスト: 共有テキストを優先し、なければ取得した説明（Xのポスト本文）を使う
        const defaultText = hasText
          ? trimmedText
          : truncateText(description, SHARED_TEXT_MAX_LENGTH);
        const textCands: Array<{ label: string; value: string }> = [];
        if (hasText) {
          textCands.push({ label: "共有テキスト", value: trimmedText });
        }
        if (description && description !== trimmedText) {
          textCands.push({
            label: isXPostUrl(trimmedUrl) ? "Xポスト本文" : "ページの説明",
            value: truncateText(description, SHARED_TEXT_MAX_LENGTH),
          });
        }
        setTextCandidates(textCands.filter((c) => c.value !== defaultText));
        if (!hasText && description) {
          setInputText(defaultText);
        }
        lastRawTitleRef.current = rawTitle;
        const body = buildBody(bodyTemplate, trimmedUrl, defaultText, rawTitle);
        let project = defaultProject || projects[0]?.name || "";
        let aiResult: string | null = null;
        if (projects.length === 0 || !project) {
          setTitle(finalTitle);
          setGeneratedBody(body);
          setSelectedProject(null);
          setAiSuggestedProject(null);
          setPageExists(null);
          setCosenseUrl(null);
          setError("プロジェクトが登録されていません。設定から追加してください");
          return;
        }
        if (aiProvider === "openRouter" && openRouterApiKey.trim()) {
          const orProject = await selectProjectWithOpenRouter(
            projects,
            rawTitle,
            openRouterApiKey,
            openRouterModel,
          );
          if (orProject) {
            project = orProject;
            aiResult = orProject;
          }
        } else if (aiProvider === "windowAi") {
          const aiProject = await selectProjectWithAi(projects, rawTitle);
          if (aiProject) {
            project = aiProject;
            aiResult = aiProject;
          }
        }
        const selectedProjectData = projects.find((p) => p.name === project);
        let exists: boolean | null = null;
        if (selectedProjectData?.isPublic) {
          setCheckingExists(true);
          try {
            exists = await checkPageExists(project, finalTitle, true);
          } finally {
            setCheckingExists(false);
          }
        }
        setPageExists(exists);
        const url = buildCosenseUrl(project, finalTitle, body);
        setTitle(finalTitle);
        setCosenseUrl(url);
        setSelectedProject(project);
        setGeneratedBody(body);
        setAiSuggestedProject(aiResult);
        setLastFetchedUrl(hasUrl ? trimmedUrl : "");
        setLastFetchedText(trimmedText);
      } catch (e) {
        setError(e instanceof Error ? e.message : "タイトルの取得に失敗しました");
      } finally {
        setLoading(false);
      }
    },
    [
      defaultProject,
      aiProvider,
      projects,
      openRouterApiKey,
      openRouterModel,
      titlePrefix,
      bodyTemplate,
      windowAiAvailable,
    ],
  );

  useEffect(() => {
    if (window.location.hash === "#usage") {
      setView("usage");
    } else if (window.location.hash === "#settings") {
      setView("settings");
    }
    const shared = extractSharedContent(window.location.search);
    if (shared.url || shared.text || shared.title) {
      initialSharedRef.current = shared;
      if (shared.url) {
        setInputUrl(shared.url);
      }
      if (shared.text) {
        setInputText(shared.text);
      }
      setView("generate");
    }
  }, []);

  useEffect(() => {
    const trimmedUrl = inputUrl.trim();
    const trimmedText = truncateText(inputText.trim(), SHARED_TEXT_MAX_LENGTH);

    if (!trimmedUrl && !trimmedText) {
      setTitle(null);
      setCosenseUrl(null);
      setSelectedProject(null);
      setGeneratedBody(null);
      setAiSuggestedProject(null);
      setPageExists(null);
      setCheckingExists(false);
      setError(null);
      setCopied(false);
      setLastFetchedUrl(null);
      setLastFetchedText(null);
      setTitleCandidates([]);
      setCandidateAiLoading(false);
      setShowCandidates(false);
      setTextCandidates([]);
      setShowTextCandidates(false);
      const url = new URL(window.location.href);
      const hadParam = ["url", "text", "title"].some((key) => url.searchParams.has(key));
      if (hadParam) {
        url.searchParams.delete("url");
        url.searchParams.delete("text");
        url.searchParams.delete("title");
        window.history.replaceState(null, "", url.pathname + url.search + window.location.hash);
      }
      return;
    }

    if (trimmedUrl && !isValidHttpUrl(trimmedUrl)) {
      const handler = setTimeout(() => {
        setError("http:// または https:// で始まるURLを入力してください");
      }, 400);
      return () => clearTimeout(handler);
    }

    setError(null);
    const newUrl = new URL(window.location.href);
    let changed = false;
    if (newUrl.searchParams.get("url") !== trimmedUrl) {
      if (trimmedUrl) {
        newUrl.searchParams.set("url", trimmedUrl);
      } else {
        newUrl.searchParams.delete("url");
      }
      changed = true;
    }
    if (newUrl.searchParams.get("text") !== trimmedText) {
      if (trimmedText) {
        newUrl.searchParams.set("text", trimmedText);
      } else {
        newUrl.searchParams.delete("text");
      }
      changed = true;
    }
    if (changed) {
      newUrl.searchParams.delete("title");
      window.history.replaceState(null, "", newUrl.pathname + newUrl.search + newUrl.hash);
    }
  }, [inputUrl, inputText]);

  // Web Share (share_target)時はタイトル抽出を自動実行
  useEffect(() => {
    if (projectsLoading) return;
    if (hasAutoGeneratedRef.current) return;
    const shared = initialSharedRef.current;
    if (!shared) return;
    if (shared.url && !isValidHttpUrl(shared.url)) return;
    if (inputUrl.trim() !== (shared.url ?? "")) return;
    if (inputText.trim() !== (shared.text ?? "")) return;
    if (loading || title !== null || cosenseUrl !== null) return;
    hasAutoGeneratedRef.current = true;
    void generate(shared.url ?? "", shared.text ?? "", shared.title ?? "");
  }, [projectsLoading, inputUrl, inputText, loading, title, cosenseUrl, generate]);

  useEffect(() => {
    if (!showCandidates && !showTextCandidates) return;
    const onPointerDown = (e: MouseEvent) => {
      const target = e.target as Node;
      if (
        candidatesPopoverRef.current?.contains(target) ||
        candidatesButtonRef.current?.contains(target) ||
        textCandidatesPopoverRef.current?.contains(target) ||
        textCandidatesButtonRef.current?.contains(target)
      ) {
        return;
      }
      setShowCandidates(false);
      setShowTextCandidates(false);
    };
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        setShowCandidates(false);
        setShowTextCandidates(false);
      }
    };
    document.addEventListener("mousedown", onPointerDown);
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("mousedown", onPointerDown);
      document.removeEventListener("keydown", onKeyDown);
    };
  }, [showCandidates, showTextCandidates]);

  const handleViewChange = (next: View) => {
    setView(next);
    if (next === "usage") {
      window.location.hash = "#usage";
    } else if (next === "settings") {
      window.location.hash = "#settings";
    } else {
      window.location.hash = "";
    }
    if (next === "settings") {
      void loadProjects();
    }
  };

  // 詳細のリンクはトグルでbodyの有無を切り替える（Open inボタンは常にbody付き）
  const linkUrl =
    cosenseUrl === null ? null : includeBodyInLink ? cosenseUrl : stripCosenseBody(cosenseUrl);

  const handleIncludeBodyChange = (checked: boolean) => {
    setIncludeBodyInLink(checked);
    setCopied(false);
  };

  const handleCopy = async () => {
    if (!linkUrl) return;
    try {
      await navigator.clipboard.writeText(linkUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setError("クリップボードへのコピーに失敗しました");
    }
  };

  const closeProjectDialog = useCallback(() => {
    setIsProjectDialogOpen(false);
    setProjectForm({ name: "", description: "", isPublic: false });
    setEditingName(null);
    setProjectError(null);
  }, []);

  const openAddDialog = useCallback(() => {
    setProjectForm({ name: "", description: "", isPublic: false });
    setEditingName(null);
    setProjectError(null);
    setIsProjectDialogOpen(true);
  }, []);

  const openEditDialog = useCallback((project: Project) => {
    setProjectForm({
      name: project.name,
      description: project.description,
      isPublic: project.isPublic,
    });
    setEditingName(project.name);
    setProjectError(null);
    setIsProjectDialogOpen(true);
  }, []);

  const handleProjectSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setProjectError(null);
    const name = projectForm.name.trim();
    const description = projectForm.description.trim();
    if (!name) {
      setProjectError("プロジェクト名は必須です");
      return;
    }
    if (description.length > 100) {
      setProjectError("説明は100文字以内で入力してください");
      return;
    }
    const project: Project = { name, description, isPublic: projectForm.isPublic };
    try {
      if (editingName) {
        await updateProject(editingName, project);
      } else {
        await addProject(project);
      }
      setIsProjectDialogOpen(false);
      setProjectForm({ name: "", description: "", isPublic: false });
      setEditingName(null);
      await loadProjects();
    } catch (err) {
      setProjectError(err instanceof Error ? err.message : "保存に失敗しました");
    }
  };

  const handleEdit = (project: Project) => {
    openEditDialog(project);
  };

  useEffect(() => {
    if (!isProjectDialogOpen) return;
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        closeProjectDialog();
      }
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [isProjectDialogOpen, closeProjectDialog]);

  const handleDelete = async (name: string) => {
    if (!confirm(`プロジェクト "${name}" を削除しますか？`)) {
      return;
    }
    try {
      await deleteProject(name);
      await loadProjects();
    } catch (err) {
      setProjectError(err instanceof Error ? err.message : "削除に失敗しました");
    }
  };

  const handleSetDefault = async (name: string) => {
    try {
      await setDefaultProject(name);
      setDefaultProjectState(name);
    } catch (err) {
      setProjectError(err instanceof Error ? err.message : "デフォルト設定に失敗しました");
    }
  };

  const handleAiProviderChange = async (provider: AiProvider) => {
    try {
      await setAiProvider(provider);
      setAiProviderState(provider);
    } catch (err) {
      setProjectError(err instanceof Error ? err.message : "設定の保存に失敗しました");
    }
  };

  const handleOpenRouterApiKeyChange = async (key: string) => {
    setOpenRouterApiKeyState(key);
    try {
      await setOpenRouterApiKey(key);
    } catch (err) {
      setProjectError(err instanceof Error ? err.message : "設定の保存に失敗しました");
    }
  };

  const handleOpenRouterModelChange = async (model: string) => {
    setOpenRouterModelState(model);
    try {
      await setOpenRouterModel(model);
    } catch (err) {
      setProjectError(err instanceof Error ? err.message : "設定の保存に失敗しました");
    }
  };

  const handleTitlePrefixChange = async (prefix: string) => {
    setTitlePrefixState(prefix);
    try {
      await setTitlePrefix(prefix);
    } catch (err) {
      setProjectError(err instanceof Error ? err.message : "設定の保存に失敗しました");
    }
  };

  const handleLinkOpenModeChange = async (mode: LinkOpenMode) => {
    setLinkOpenModeState(mode);
    try {
      await setLinkOpenMode(mode);
    } catch (err) {
      setProjectError(err instanceof Error ? err.message : "設定の保存に失敗しました");
    }
  };

  const handleBodyTemplateChange = async (template: string) => {
    setBodyTemplateState(template);
    try {
      await setBodyTemplate(template);
    } catch (err) {
      setProjectError(err instanceof Error ? err.message : "設定の保存に失敗しました");
    }
  };

  const handleProjectChange = useCallback(
    async (newProject: string) => {
      setSelectedProject(newProject);
      setCopied(false);
      if (title && generatedBody) {
        const newUrl = buildCosenseUrl(newProject, title, generatedBody);
        setCosenseUrl(newUrl);
        const projData = projects.find((p) => p.name === newProject);
        if (projData?.isPublic) {
          setCheckingExists(true);
          try {
            const exists = await checkPageExists(newProject, title, true);
            setPageExists(exists);
          } finally {
            setCheckingExists(false);
          }
        } else {
          setPageExists(null);
        }
      }
    },
    [title, generatedBody, projects],
  );

  const handleTitleChange = useCallback(
    async (newTitle: string) => {
      setTitle(newTitle);
      setCopied(false);
      const trimmed = newTitle.trim();
      if (!trimmed) {
        setCosenseUrl(null);
        setPageExists(null);
        setCheckingExists(false);
        return;
      }
      const effectiveProject = selectedProject || defaultProject || projects[0]?.name || "";
      if (!effectiveProject || projects.length === 0) {
        setCosenseUrl(null);
        setPageExists(null);
        setCheckingExists(false);
        if (!generatedBody && (inputUrl.trim() || inputText.trim())) {
          const fallbackBody = inputUrl.trim() || inputText.trim();
          setGeneratedBody(fallbackBody);
        }
        return;
      }
      if (!generatedBody || !selectedProject) {
        const fallbackBody = generatedBody ?? (inputUrl.trim() || inputText.trim());
        if (!fallbackBody) return;
        const newUrl = buildCosenseUrl(effectiveProject, newTitle, fallbackBody);
        setCosenseUrl(newUrl);
        if (!generatedBody) {
          setGeneratedBody(fallbackBody);
          if (!selectedProject) {
            setSelectedProject(effectiveProject);
          }
        }
        const projData = projects.find((p) => p.name === effectiveProject);
        if (projData?.isPublic) {
          setCheckingExists(true);
          try {
            const exists = await checkPageExists(effectiveProject, newTitle, true);
            setPageExists(exists);
          } finally {
            setCheckingExists(false);
          }
        } else {
          setPageExists(null);
        }
        return;
      }
      const newUrl = buildCosenseUrl(selectedProject, newTitle, generatedBody);
      setCosenseUrl(newUrl);
      const projData = projects.find((p) => p.name === selectedProject);
      if (projData?.isPublic) {
        setCheckingExists(true);
        try {
          const exists = await checkPageExists(selectedProject, newTitle, true);
          setPageExists(exists);
        } finally {
          setCheckingExists(false);
        }
      } else {
        setPageExists(null);
      }
    },
    [generatedBody, selectedProject, projects, inputUrl, inputText, defaultProject],
  );

  const trimmedInputUrl = inputUrl.trim();
  const trimmedInputText = inputText.trim();
  const isValidUrl = isValidHttpUrl(trimmedInputUrl);
  const showTitleField = loading || title !== null || isValidUrl || trimmedInputText !== "";
  const showCosenseActions = cosenseUrl !== null && title !== null && title.trim() !== "";
  const isRefreshDisabled =
    loading ||
    (!trimmedInputUrl && !trimmedInputText) ||
    (trimmedInputUrl !== "" && !isValidUrl) ||
    (trimmedInputUrl === (lastFetchedUrl ?? "") && trimmedInputText === (lastFetchedText ?? ""));

  const handleCandidateSelect = useCallback(
    (value: string) => {
      const newTitle = `${titlePrefix}${value}`;
      setShowCandidates(false);
      void handleTitleChange(newTitle);
    },
    [titlePrefix, handleTitleChange],
  );

  // 本文テキストが変わったときに本文とCosense URLを再構築する
  const rebuildBodyFromText = useCallback(
    (text: string) => {
      if (!title || !generatedBody) return;
      const effectiveProject = selectedProject || defaultProject || projects[0]?.name || "";
      if (!effectiveProject) return;
      const body = buildBody(bodyTemplate, lastFetchedUrl ?? "", text, lastRawTitleRef.current);
      setGeneratedBody(body);
      setCosenseUrl(buildCosenseUrl(effectiveProject, title, body));
      setCopied(false);
    },
    [title, generatedBody, selectedProject, defaultProject, projects, bodyTemplate, lastFetchedUrl],
  );

  const handleTextCandidateSelect = useCallback(
    (value: string) => {
      setShowTextCandidates(false);
      setInputText(value);
      rebuildBodyFromText(value);
    },
    [rebuildBodyFromText],
  );

  const handleInputTextChange = useCallback(
    (value: string) => {
      setInputText(value);
      rebuildBodyFromText(value);
    },
    [rebuildBodyFromText],
  );

  const hasCandidates = titleCandidates.length > 0;
  const isCandidatesButtonDisabled = loading || (!hasCandidates && !candidateAiLoading);
  const hasTextCandidates = textCandidates.length > 0;
  const isTextCandidatesButtonDisabled = loading || !hasTextCandidates;

  return (
    <div className="share-root">
      <main className="share-container">
        {view === "generate" ? (
          <>
            <div className="share-form">
              <label htmlFor="url-input" className="share-label">
                共有元URL
              </label>
              <div className="share-input-row">
                <input
                  id="url-input"
                  type="url"
                  inputMode="url"
                  placeholder="https://example.com/article"
                  value={inputUrl}
                  onChange={(e) => setInputUrl(e.target.value)}
                  className="share-input"
                  autoComplete="off"
                  spellCheck={false}
                />
              </div>

              <div className="share-label-row">
                <label htmlFor="text-input" className="share-label">
                  本文テキスト
                </label>
                <div className="share-text-actions">
                  <div className="share-candidates-wrapper">
                    <button
                      ref={textCandidatesButtonRef}
                      type="button"
                      className="share-candidates-button"
                      onClick={() => setShowTextCandidates((v) => !v)}
                      disabled={isTextCandidatesButtonDisabled}
                      aria-expanded={showTextCandidates}
                      aria-haspopup="menu"
                      aria-label="他のテキスト候補を表示"
                    >
                      他の候補
                      <svg
                        width="12"
                        height="12"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        aria-hidden="true"
                      >
                        <polyline points="6 9 12 15 18 9" />
                      </svg>
                    </button>
                    {showTextCandidates && (
                      <div
                        ref={textCandidatesPopoverRef}
                        className="share-candidates-popover"
                        role="menu"
                      >
                        {textCandidates.length === 0 ? (
                          <p className="share-candidates-empty">候補がありません</p>
                        ) : (
                          textCandidates.map((c) => (
                            <button
                              key={`${c.label}:${c.value}`}
                              type="button"
                              className="share-candidates-item"
                              role="menuitem"
                              onClick={() => handleTextCandidateSelect(c.value)}
                            >
                              <span className="share-candidates-label">{c.label}</span>
                              <span className="share-candidates-value">{c.value}</span>
                            </button>
                          ))
                        )}
                      </div>
                    )}
                  </div>
                </div>
              </div>
              <textarea
                id="text-input"
                value={inputText}
                onChange={(e) => handleInputTextChange(e.target.value)}
                className="share-input"
                rows={3}
                placeholder="共有するテキスト（任意、URLと併用可）"
                autoComplete="off"
              />

              {showTitleField && (
                <div className="share-project-field">
                  <div className="share-label-row">
                    <label htmlFor="title-input" className="share-label">
                      タイトル
                    </label>
                    <div className="share-title-actions">
                      <div className="share-candidates-wrapper">
                        <button
                          ref={candidatesButtonRef}
                          type="button"
                          className="share-candidates-button"
                          onClick={() => setShowCandidates((v) => !v)}
                          disabled={isCandidatesButtonDisabled}
                          aria-expanded={showCandidates}
                          aria-haspopup="menu"
                          aria-label="他の候補を表示"
                        >
                          他の候補
                          <svg
                            width="12"
                            height="12"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            aria-hidden="true"
                          >
                            <polyline points="6 9 12 15 18 9" />
                          </svg>
                        </button>
                        {showCandidates && (
                          <div
                            ref={candidatesPopoverRef}
                            className="share-candidates-popover"
                            role="menu"
                          >
                            {titleCandidates.length === 0 && !candidateAiLoading ? (
                              <p className="share-candidates-empty">候補がありません</p>
                            ) : (
                              <>
                                {titleCandidates.map((c) => (
                                  <button
                                    key={`${c.label}:${c.value}`}
                                    type="button"
                                    className="share-candidates-item"
                                    role="menuitem"
                                    onClick={() => handleCandidateSelect(c.value)}
                                  >
                                    <span className="share-candidates-label">{c.label}</span>
                                    <span className="share-candidates-value">{c.value}</span>
                                  </button>
                                ))}
                                {candidateAiLoading && (
                                  <p className="share-candidates-loading">AI生成中...</p>
                                )}
                              </>
                            )}
                          </div>
                        )}
                      </div>
                      <button
                        type="button"
                        className={`share-title-refresh${loading ? " is-loading" : ""}`}
                        onClick={() => void generate(trimmedInputUrl, trimmedInputText)}
                        disabled={isRefreshDisabled}
                        title="タイトルを取得"
                        aria-label="タイトルを取得"
                        aria-busy={loading}
                      >
                        <svg
                          width="16"
                          height="16"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          aria-hidden="true"
                        >
                          <polyline points="23 4 23 10 17 10" />
                          <polyline points="1 20 1 14 7 14" />
                          <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15" />
                        </svg>
                      </button>
                    </div>
                  </div>
                  <input
                    id="title-input"
                    type="text"
                    value={title ?? ""}
                    onChange={(e) => void handleTitleChange(e.target.value)}
                    disabled={loading}
                    className="share-input"
                    placeholder={loading ? "タイトルを取得中..." : "タイトルを入力"}
                    autoComplete="off"
                    spellCheck={false}
                  />
                </div>
              )}

              {projectsLoading ? (
                <p className="share-loading">プロジェクトを読み込み中...</p>
              ) : projects.length === 0 ? (
                <div className="share-project-field">
                  <label htmlFor="project-select" className="share-label">
                    作成先プロジェクト
                  </label>
                  <p className="share-error" role="alert">
                    プロジェクトが登録されていません。
                    <button
                      type="button"
                      className="share-footer-link"
                      onClick={() => handleViewChange("settings")}
                    >
                      設定
                    </button>
                    から追加してください
                  </p>
                </div>
              ) : (
                <div className="share-project-field">
                  <label htmlFor="project-select" className="share-label">
                    作成先プロジェクト
                  </label>
                  <select
                    id="project-select"
                    value={selectedProject || defaultProject || projects[0]?.name || ""}
                    onChange={(e) => void handleProjectChange(e.target.value)}
                    className="share-input share-select"
                  >
                    {projects.map((p) => (
                      <option key={p.name} value={p.name}>
                        {p.name} ({p.isPublic ? "public" : "private"})
                        {p.name === defaultProject ? " - デフォルト" : ""}
                        {aiSuggestedProject === p.name ? " - AI提案" : ""}
                      </option>
                    ))}
                  </select>
                  {aiSuggestedProject &&
                    selectedProject &&
                    aiSuggestedProject !== selectedProject && (
                      <p className="share-project-select">
                        AIの提案: <code>{aiSuggestedProject}</code> から手動で変更しました
                      </p>
                    )}
                  {!aiSuggestedProject &&
                    selectedProject &&
                    selectedProject !== defaultProject &&
                    cosenseUrl && (
                      <p className="share-project-select">
                        デフォルト <code>{defaultProject}</code> から手動で変更しました
                      </p>
                    )}
                </div>
              )}
              {error && (
                <p className="share-error" role="alert">
                  {error}
                </p>
              )}

              {showCosenseActions && (
                <>
                  <a
                    href={cosenseUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="share-button primary large"
                    onClick={(e) => {
                      // PWAとして起動している場合は、アプリ内ブラウザではなく
                      // ブラウザ / Cosense PWA で開くようOSに委ねる
                      if (openCosenseUrl(cosenseUrl, linkOpenMode)) {
                        e.preventDefault();
                      }
                    }}
                  >
                    Open in {selectedProject || defaultProject || projects[0]?.name || ""}
                  </a>
                  {checkingExists && <p className="share-loading">存在チェック中...</p>}
                  {pageExists && (
                    <p className="share-warning" role="alert">
                      ⚠️
                      このタイトルのページは既に存在します。リンクを開くと既存ページに追記されます。
                    </p>
                  )}
                  <details className="share-details">
                    <summary>詳細を表示</summary>
                    <dl className="share-result-list">
                      <div>
                        <dt>Cosenseリンク</dt>
                        <dd>
                          <label className="share-toggle">
                            <input
                              type="checkbox"
                              role="switch"
                              checked={includeBodyInLink}
                              onChange={(e) => handleIncludeBodyChange(e.target.checked)}
                            />
                            <span className="share-toggle-track" aria-hidden="true" />
                            <span className="share-toggle-label">bodyを含める</span>
                          </label>
                          <div className="share-link-wrapper">
                            <a
                              href={linkUrl ?? undefined}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="share-link"
                              onClick={(e) => {
                                e.preventDefault();
                                void handleCopy();
                              }}
                              title={copied ? "コピーしました" : "クリックしてコピー"}
                              role="button"
                              tabIndex={0}
                              onKeyDown={(e) => {
                                if (e.key === "Enter" || e.key === " ") {
                                  e.preventDefault();
                                  void handleCopy();
                                }
                              }}
                            >
                              {linkUrl}
                            </a>
                            <button
                              type="button"
                              onClick={() => void handleCopy()}
                              className="share-copy-icon"
                              aria-label={copied ? "コピーしました" : "リンクをコピー"}
                              title={copied ? "コピーしました" : "リンクをコピー"}
                            >
                              {copied ? (
                                <svg
                                  width="16"
                                  height="16"
                                  viewBox="0 0 24 24"
                                  fill="none"
                                  stroke="currentColor"
                                  strokeWidth="2"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  aria-hidden="true"
                                >
                                  <polyline points="20 6 9 17 4 12" />
                                </svg>
                              ) : (
                                <svg
                                  width="16"
                                  height="16"
                                  viewBox="0 0 24 24"
                                  fill="none"
                                  stroke="currentColor"
                                  strokeWidth="2"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  aria-hidden="true"
                                >
                                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                                  <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v3" />
                                </svg>
                              )}
                            </button>
                          </div>
                          {copied && <span className="share-copy-feedback">コピーしました</span>}
                        </dd>
                      </div>
                      {trimmedInputUrl && (
                        <div>
                          <dt>共有元URL</dt>
                          <dd>{trimmedInputUrl}</dd>
                        </div>
                      )}
                      {trimmedInputText && (
                        <div>
                          <dt>本文テキスト</dt>
                          <dd className="share-text-preview">{trimmedInputText}</dd>
                        </div>
                      )}
                    </dl>
                  </details>
                </>
              )}
            </div>

            <footer className="share-footer">
              <button
                type="button"
                className="share-footer-link"
                onClick={() => handleViewChange("settings")}
              >
                プロジェクト設定
              </button>
              <span className="share-footer-separator">·</span>
              <button
                type="button"
                className="share-footer-link"
                onClick={() => handleViewChange("usage")}
              >
                使い方を見る
              </button>
            </footer>
          </>
        ) : view === "usage" ? (
          <>
            <section className="share-usage">
              <h2>使い方</h2>
              <p className="share-usage-description">
                共有されたURLやテキストから、Cosenseページ作成リンクを生成するPWAです。
                <br />
                生成されたリンクを開くと{" "}
                <code>
                  https://scrapbox.io/{defaultProject || projects[0]?.name || "(未設定)"}
                  /&lt;title&gt;?body=&lt;body&gt;
                </code>{" "}
                で新規ページが作成されます（<code>&lt;body&gt;</code>{" "}
                は設定の本文テンプレートから生成、既存ページがある場合は追記）。
              </p>
              <p className="share-project">
                作成先プロジェクト: <code>{defaultProject || projects[0]?.name || "(未設定)"}</code>
                {projects.length === 0
                  ? "（設定からプロジェクトを追加してください）"
                  : "（AIがタイトルから自動選択、ドロップダウンで手動変更可能）"}
              </p>
              <ol className="share-usage-steps">
                <li>
                  PWAをインストールするとOSの共有先に表示されます。スマホ等の「共有」から
                  share2cosense
                  を選択すると、URLやテキストを自動で読み取りタイトルを取得してリンクを生成します
                </li>
                <li>
                  またはトップの「共有元URL」欄に <code>https://...</code>{" "}
                  を貼り付けます。URLと併用して「本文テキスト」欄にテキストも入力できます。タイトル欄が表示されるので、必要に応じて編集や右側の更新ボタンで再取得ができます
                </li>
                <li>
                  作成先プロジェクトはAI（設定で選択）の提案またはデフォルトプロジェクトが自動選択されます。ドロップダウンで手動変更できます
                  （<code>public</code> の場合は既存ページの存在チェックが表示されます）
                </li>
                <li>
                  「Open in {defaultProject || projects[0]?.name || "プロジェクト"}
                  」ボタンでCosenseを開いてページを作成します。リンクは「詳細を表示」からコピーもできます（「bodyを含める」トグルで
                  <code>?body=</code>
                  の有無を切り替えられます。初期値はオフで、本文なしのページ作成リンクになります）
                </li>
              </ol>
              <details>
                <summary>Cosenseリンクの開き方</summary>
                <p>
                  share2cosenseをPWAとしてインストールしている場合、通常のリンクはアプリ内ブラウザで開かれ、Cosenseがshare2cosenseの中に表示されてしまいます。
                  そのため「Open in
                  ...」ボタンはPWAとして起動しているときだけリンクをOSに渡し、Cosense
                  PWAがインストールされていればそちらで、なければ既定のブラウザで開きます。
                  ブラウザのタブから使っているときは、これまで通り新しいタブで開きます。
                </p>
                <p>
                  挙動は設定の「Cosenseリンクの開き方」で変更できます（<code>自動</code>/
                  <code>共有シート</code>/<code>新しいタブ</code>）。
                </p>
              </details>
              <details>
                <summary>タイトル・本文のカスタマイズ</summary>
                <p>
                  設定の「タイトル接頭辞」でタイトルの先頭に固定文字列を付与できます。「本文テンプレート」では{" "}
                  <code>{"{{url}}"}</code>（共有元URL）、<code>{"{{text}}"}</code>
                  （本文テキスト）、<code>{"{{title}}"}</code>
                  （取得したタイトル）、<code>{"{{date}}"}</code>
                  （YYYY-MM-DD）を使って本文をカスタマイズできます。初期値は{" "}
                  <code>{"{{url}}"}</code> です。URLが共有されていない場合は{" "}
                  <code>{"{{url}}"}</code> は空文字になります。
                </p>
                <p>
                  本文テキスト欄には共有テキストが入り、URLだけを共有した場合はページの説明（Xのポストでは本文全体）が入ります。「他の候補」から共有テキストとページの説明を切り替えられます。タイトルは本文テキストから生成します。
                  AI（設定の「プロジェクト自動選択」で選んだもの）が有効なときはテキスト（URLが共有されている場合はそれも参照）からタイトルを生成し、
                  AIを使わない設定や生成に失敗した場合はテキストの先頭
                  {X_TITLE_MAX_LENGTH}文字を使用します。テキストは{SHARED_TEXT_MAX_LENGTH}
                  文字まで本文に含められます。
                </p>
                <p>
                  Xのポストを共有した場合、タイトルには <code>og:title</code>（
                  <code>{"{ユーザ名} on X"}</code>）ではなくポスト本文を使用します。
                  AI（設定の「プロジェクト自動選択」で選んだもの）が有効なときは本文からタイトルを生成し、
                  AIを使わない設定や生成に失敗した場合は本文の先頭
                  {X_TITLE_MAX_LENGTH}文字を使用します。いずれの場合も全文は{" "}
                  <code>{"{{text}}"}</code> で本文に含められます。
                </p>
              </details>
              <details>
                <summary>Share Targetの仕様（GET）</summary>
                <p>
                  <code>?url=&lt;url&gt;&amp;text=&lt;text&gt;&amp;title=&lt;title&gt;</code>{" "}
                  で共有を受け取ります。URLの優先順位は <code>url</code> ＞ <code>text</code> 内URL
                  ＞ <code>title</code> です。<code>text</code> は共有テキストとして{" "}
                  <code>{"{{text}}"}</code> に埋め込まれます。PWAの{" "}
                  <code>manifest share_target</code> は{" "}
                  <code>action: &quot;/&quot; method: GET</code> で設定済みです。
                </p>
              </details>
            </section>
            <footer className="share-footer">
              <button
                type="button"
                className="share-footer-link"
                onClick={() => handleViewChange("generate")}
              >
                リンク生成に戻る
              </button>
            </footer>
          </>
        ) : (
          <>
            <section className="share-settings">
              <h2>プロジェクト設定</h2>
              <p className="share-settings-description">
                作成先プロジェクトを追加・編集・削除できます。説明は100文字以内、publicフラグは存在チェックに使用されます。
              </p>

              <div className="share-ai-settings">
                <h3>AIによる自動選択</h3>
                <div className="share-project-field">
                  <label htmlFor="ai-provider">プロジェクト自動選択</label>
                  <select
                    id="ai-provider"
                    value={aiProvider === "windowAi" && !windowAiAvailable ? "none" : aiProvider}
                    onChange={(e) => void handleAiProviderChange(e.target.value as AiProvider)}
                    className="share-input share-select"
                  >
                    <option value="none">自動選択しない</option>
                    {windowAiAvailable && (
                      <option value="windowAi">ブラウザAI (LanguageModel)</option>
                    )}
                    <option value="openRouter">OpenRouter</option>
                  </select>
                  {!windowAiAvailable && (
                    <p className="share-error" style={{ marginTop: "8px" }} role="alert">
                      この環境ではブラウザAI（LanguageModel)は利用できません
                    </p>
                  )}
                  <p className="share-settings-description" style={{ marginTop: "8px" }}>
                    プロジェクトの説明と記事タイトルからAIが適切なプロジェクトを自動選択します。AIで選択できなかった場合はデフォルトプロジェクトが使用されます。
                  </p>
                  <p className="share-settings-description" style={{ marginTop: "8px" }}>
                    ここでAIを選ぶと、共有テキスト（Xのポストを含む）からタイトルも生成します。「自動選択しない」の場合や生成に失敗した場合は、テキストの先頭
                    {X_TITLE_MAX_LENGTH}文字がタイトルになります。
                  </p>
                </div>
                {aiProvider === "openRouter" && (
                  <>
                    <div className="share-project-field">
                      <label htmlFor="openrouter-key">APIキー</label>
                      <input
                        id="openrouter-key"
                        type="password"
                        value={openRouterApiKey}
                        onChange={(e) => void handleOpenRouterApiKeyChange(e.target.value)}
                        placeholder="sk-or-v1-..."
                        className="share-input"
                      />
                    </div>
                    <div className="share-project-field">
                      <label htmlFor="openrouter-model">モデル</label>
                      <input
                        id="openrouter-model"
                        type="text"
                        value={openRouterModel}
                        onChange={(e) => void handleOpenRouterModelChange(e.target.value)}
                        placeholder="google/gemini-3.7-flash"
                        className="share-input"
                      />
                    </div>
                    <p className="share-settings-description" style={{ marginTop: "8px" }}>
                      OpenRouter経由で選択したモデルで自動選択します。APIキーはIndexedDBに保存されます。
                    </p>
                  </>
                )}
              </div>

              <div className="share-ai-settings">
                <h3>Cosenseリンクの開き方</h3>
                <div className="share-project-field">
                  <label htmlFor="link-open-mode">「Open in」ボタンの動作</label>
                  <select
                    id="link-open-mode"
                    value={linkOpenMode}
                    onChange={(e) => void handleLinkOpenModeChange(e.target.value as LinkOpenMode)}
                    className="share-input share-select"
                  >
                    <option value="auto">自動（OSに任せる）</option>
                    <option value="share">共有シートで開く先を選ぶ</option>
                    <option value="newTab">新しいタブで開く</option>
                  </select>
                  <p className="share-settings-description" style={{ marginTop: "8px" }}>
                    「自動」はPWAとして起動しているときだけOSにリンクを渡し、Cosense
                    PWA（未インストールならブラウザ）で開きます。share2cosenseのアプリ内ブラウザで開いてしまう場合は「共有シート」を、常に同じ挙動にしたい場合は「新しいタブ」を選んでください。
                  </p>
                </div>
              </div>

              <div className="share-ai-settings">
                <h3>タイトルと本文のカスタマイズ</h3>
                <div className="share-project-field">
                  <label htmlFor="title-prefix">タイトル接頭辞（任意）</label>
                  <input
                    id="title-prefix"
                    type="text"
                    value={titlePrefix}
                    onChange={(e) => void handleTitlePrefixChange(e.target.value)}
                    placeholder="例: [WebClip] "
                    className="share-input"
                  />
                </div>
                <div className="share-project-field">
                  <label htmlFor="body-template">
                    本文テンプレート（{"{{url}}"}, {"{{text}}"}, {"{{title}}"}, {"{{date}}"}{" "}
                    が使用可能）
                  </label>
                  <textarea
                    id="body-template"
                    value={bodyTemplate}
                    onChange={(e) => void handleBodyTemplateChange(e.target.value)}
                    placeholder="{{url}}"
                    className="share-input"
                    rows={3}
                    style={{ resize: "vertical" }}
                  />
                  <span className="share-project-counter">
                    プレビュー:{" "}
                    {bodyTemplate
                      .replaceAll("{{url}}", "https://example.com")
                      .replaceAll("{{text}}", "Example text")
                      .replaceAll("{{title}}", "Example Title")
                      .replaceAll("{{date}}", new Date().toISOString().slice(0, 10))}
                  </span>
                </div>
              </div>

              <div className="share-project-list">
                <div className="share-project-list-header">
                  <h3>登録済みプロジェクト</h3>
                  <button type="button" className="share-button small" onClick={openAddDialog}>
                    プロジェクトを追加
                  </button>
                </div>
                {projectError && !isProjectDialogOpen && (
                  <p className="share-error" role="alert" style={{ marginBottom: "12px" }}>
                    {projectError}
                  </p>
                )}
                {projectsLoading ? (
                  <p className="share-loading">読み込み中...</p>
                ) : projects.length === 0 ? (
                  <p>プロジェクトがありません</p>
                ) : (
                  <ul>
                    {projects.map((project) => (
                      <li
                        key={project.name}
                        className={`share-project-item ${defaultProject === project.name ? "is-default" : ""}`}
                      >
                        <div className="share-project-info">
                          <strong>{project.name}</strong>
                          <span
                            className={`share-project-badge ${project.isPublic ? "public" : "private"}`}
                          >
                            {project.isPublic ? "public" : "private"}
                          </span>
                          {defaultProject === project.name && (
                            <span className="share-project-default">デフォルト</span>
                          )}
                          {project.description && (
                            <p className="share-project-desc">{project.description}</p>
                          )}
                        </div>
                        <div className="share-project-item-actions">
                          <label className="share-project-default-radio">
                            <input
                              type="radio"
                              name="defaultProject"
                              checked={defaultProject === project.name}
                              onChange={() => void handleSetDefault(project.name)}
                            />
                            デフォルト
                          </label>
                          <button
                            type="button"
                            className="share-button secondary small"
                            onClick={() => handleEdit(project)}
                          >
                            編集
                          </button>
                          <button
                            type="button"
                            className="share-button secondary small"
                            onClick={() => void handleDelete(project.name)}
                          >
                            削除
                          </button>
                        </div>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
              {isProjectDialogOpen && (
                <div className="share-dialog-overlay" onClick={closeProjectDialog}>
                  <div
                    className="share-dialog"
                    role="dialog"
                    aria-modal="true"
                    aria-labelledby="project-dialog-title"
                    onClick={(e) => e.stopPropagation()}
                  >
                    <div className="share-dialog-header">
                      <h3 id="project-dialog-title">
                        {editingName ? "プロジェクトを編集" : "プロジェクトを追加"}
                      </h3>
                      <button
                        type="button"
                        className="share-dialog-close"
                        onClick={closeProjectDialog}
                        aria-label="閉じる"
                      >
                        ×
                      </button>
                    </div>
                    <form className="share-dialog-form" onSubmit={handleProjectSubmit}>
                      <div className="share-project-field">
                        <label htmlFor="project-name">プロジェクト名 *</label>
                        <input
                          id="project-name"
                          type="text"
                          value={projectForm.name}
                          onChange={(e) =>
                            setProjectForm((prev) => ({ ...prev, name: e.target.value }))
                          }
                          placeholder="my-project"
                          className="share-input"
                          required
                          autoFocus
                        />
                      </div>
                      <div className="share-project-field">
                        <label htmlFor="project-description">説明（任意, 100文字以内）</label>
                        <input
                          id="project-description"
                          type="text"
                          value={projectForm.description}
                          onChange={(e) =>
                            setProjectForm((prev) => ({ ...prev, description: e.target.value }))
                          }
                          placeholder="例: 個人用のプライベートプロジェクト"
                          className="share-input"
                          maxLength={100}
                        />
                        <span className="share-project-counter">
                          {projectForm.description.length}/100
                        </span>
                      </div>
                      <label className="share-project-checkbox">
                        <input
                          type="checkbox"
                          checked={projectForm.isPublic}
                          onChange={(e) =>
                            setProjectForm((prev) => ({ ...prev, isPublic: e.target.checked }))
                          }
                        />
                        publicプロジェクト
                      </label>
                      {projectError && (
                        <p className="share-error" role="alert">
                          {projectError}
                        </p>
                      )}
                      <div className="share-project-actions">
                        <button type="submit" className="share-button">
                          {editingName ? "更新" : "追加"}
                        </button>
                        <button
                          type="button"
                          className="share-button secondary"
                          onClick={closeProjectDialog}
                        >
                          キャンセル
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              )}
            </section>
            <footer className="share-footer">
              <button
                type="button"
                className="share-footer-link"
                onClick={() => handleViewChange("generate")}
              >
                リンク生成に戻る
              </button>
            </footer>
          </>
        )}
      </main>
      <Analytics />
    </div>
  );
}
